spring.application.name=bookingreminder

spring.datasource.url=jdbc:mysql://localhost:3306/booking_reminder
spring.datasource.username=root
spring.datasource.password=Mola11.#0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8086